name: vestium
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: CormorantGaramond
      fonts:
        - asset: assets/fonts/CormorantGaramond/CormorantGaramond-Regular.ttf
          weight: 400
        - asset: assets/fonts/CormorantGaramond/CormorantGaramond-Italic.ttf
          style: italic

    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter-ExtraLight.ttf
          weight: 200

    - family: AlexBrush
      fonts:
        - asset: assets/fonts/AlexBrush/AlexBrush-Regular.ttf
          weight: 400
