name: vestium
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^7.8.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.6

flutter:
  uses-material-design: true

  assets:
    - assets/images/logos/
    - assets/images/backgrounds/
    - assets/images/dummyData/
    - assets/images/icons/
    - assets/fonts/

  fonts:
    - family: CormorantGaramond
      fonts:
        - asset: assets/fonts/CormorantGaramond/CormorantGaramond-Regular.ttf
          weight: 400
        - asset: assets/fonts/CormorantGaramond/CormorantGaramond-Italic.ttf
          style: italic

    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter_18pt-ExtraLight.ttf
          weight: 200

    - family: AlexBrush
      fonts:
        - asset: assets/fonts/AlexBrush/AlexBrush-Regular.ttf
          weight: 400
